const router = require('express').Router();
const role = require('../middleware/roleMiddleware');
const upload = require('../middleware/uploadMiddleware');
const ctrl = require('../controllers/adminController');
const ml = require('../controllers/mlController');
router.use(role('admin'));
router.get('/dashboard', ctrl.dashboard);
router.get('/users', ctrl.users);
router.post('/officers', ctrl.createOfficer);
router.patch('/users/:id', ctrl.updateUser);
router.get('/zones', ctrl.zones);
router.post('/zones', ctrl.createZone);
router.patch('/zones/:id', ctrl.updateZone);
router.get('/categories', ctrl.categories);
router.post('/categories', ctrl.createCategory);
router.patch('/categories/:id', ctrl.updateCategory);
router.post('/dataset-upload', upload.single('file'), ctrl.datasetUpload);
router.post('/datasets/upload', upload.single('file'), ctrl.datasetUpload);
router.get('/datasets/:id/status', ctrl.datasetStatus);
router.post('/run-ml', ml.predict);
router.get('/alerts', ctrl.alertLogs);
router.get('/audit-logs', ctrl.auditLogs);
router.get('/logs', ctrl.auditLogs);
module.exports = router;
