const router = require('express').Router();
const role = require('../middleware/roleMiddleware');
const ctrl = require('../controllers/analystController');
router.use(role('analyst','admin'));
router.get('/dashboard', ctrl.dashboard);
router.get('/crime-by-zone', ctrl.reportAnalytics);
router.get('/crime-by-type', ctrl.reportAnalytics);
router.get('/hourly-trends', ctrl.timePatterns);
router.get('/crime-analysis', ctrl.crimeAnalysis);
router.get('/heatmap', ctrl.heatmap);
router.get('/zone-comparison', ctrl.zoneCompare);
router.get('/zones/compare', ctrl.zoneCompare);
router.get('/time-patterns', ctrl.timePatterns);
router.get('/ml-report', require('../controllers/mlController').report);
router.get('/risk-history', ctrl.riskHistory);
router.get('/reports', ctrl.reportAnalytics);
router.get('/export', ctrl.listExports);
router.post('/exports', ctrl.createExport);
router.get('/exports', ctrl.listExports);
module.exports = router;
