const router = require('express').Router();
const role = require('../middleware/roleMiddleware');
const ctrl = require('../controllers/officerController');
const incident = require('../controllers/incidentController');
router.get('/dashboard', role('officer'), ctrl.dashboard);
router.get('/incidents', role('officer'), ctrl.incidents);
router.get('/heatmap', role('officer'), require('../controllers/commonController').heatmapLive);
router.get('/patrol-plan', role('officer'), ctrl.patrolPlan);
router.post('/patrol-routes/generate', role('officer'), ctrl.generatePatrolRoute);
router.post('/patrol-routes/:id/start', role('officer'), ctrl.startPatrolRoute);
router.patch('/incidents/:id/status', role('officer'), incident.updateStatus);
module.exports = router;
